# 성능 평가 포함 추론 모드 프리셋
# 사용법: python main.py --config configs/presets/inference_with_evaluation.yaml --input video.mp4

execution:
  mode: "inference"
  output_dir: "output/inference_evaluation"

features:
  enable_evaluation: true      # 성능 평가 활성화
  enable_visualization: true   # 시각화 활성화

performance:
  multi_gpu: false
  multiprocess: false
  device: "cuda:0"

evaluation:
  save_options:
    detailed_results: true
    overlay_data: true
    performance_metrics: true

visualization:
  types:
    performance_charts: true
    timeline_visualization: true
    confusion_matrix: true
    overlay_videos: false  # 빠른 실행을 위해 비활성화