# 기본 추론 모드 프리셋
# 사용법: python main.py --config configs/presets/inference_basic.yaml --input video.mp4

execution:
  mode: "inference"
  output_dir: "output/inference_basic"

features:
  enable_evaluation: false
  enable_visualization: false

performance:
  multi_gpu: false
  multiprocess: false
  device: "cuda:0"

models:
  pose_estimation:
    model_name: "rtmo"
  tracking:
    tracker_name: "bytetrack"
  scoring:
    scorer_name: "region_based"
  action_classification:
    model_name: "stgcn"

modes:
  inference:
    source_type: "file"
    save_intermediate: false