# 멀티프로세스 분리 파이프라인 프리셋
# 사용법: python main.py --config configs/presets/multiprocess_separated.yaml --input data/videos

execution:
  mode: "separated"
  output_dir: "output/multiprocess_separated"

features:
  enable_evaluation: true
  enable_visualization: true

performance:
  device: "cuda:0"
  
  # 멀티프로세스 활성화
  multiprocess:
    enable: true             # 멀티프로세스 활성화
    workers: 8              # 8개 워커 프로세스
    strategy: "pipeline"     # 파이프라인 병렬화
    shared_memory: true      # 공유 메모리 사용
    queue_size: 200         # 큐 크기 증가
  
  batch_size: 4             # 배치 처리

modes:
  separated:
    stages:
      stage1_pose: true
      stage2_tracking: true  
      stage3_unification: true
    
    # 단계별 워커 배분
    multiprocess_config:
      pose_workers: 3        # 포즈 추정에 3개 워커
      tracking_workers: 3    # 트래킹에 3개 워커  
      classification_workers: 2  # 분류에 2개 워커
      batch_size: 4