# Recognizer 베이스 설정 파일
# 모든 파이프라인에서 공통으로 사용되는 설정

# 공통 모델 설정
models:
  # 포즈 추정 모델
  pose_estimation:
    model_name: "rtmo"
    config_file: "/workspace/mmpose/configs/body_2d_keypoint/rtmo/body7/rtmo-m_16xb16-600e_body7-640x640.py"
    checkpoint_path: "/workspace/mmpose/checkpoints/rtmo-m_16xb16-600e_body7-640x640-39e78cc4_20231211.pth"
    device: "cuda:0"
    batch_size: 8
    input_size: [640, 640]
    score_threshold: 0.3
  
  # 트래킹 모델
  tracking:
    tracker_name: "bytetrack"
    frame_rate: 30
    track_thresh: 0.4
    track_buffer: 50
    match_thresh: 0.4
    track_high_thresh: 0.6
    track_low_thresh: 0.1
    new_track_thresh: 0.6
  
  # 스코어링 시스템
  scoring:
    scorer_name: "region_based"
    weights:
      interaction: 0.4
      movement: 0.3
      posture: 0.1
      temporal: 0.1
      position: 0.05
      appearance: 0.05
    quality_threshold: 0.3
    min_track_length: 10
  
  # 액션 분류 모델
  action_classification:
    model_name: "stgcn"
    config_file: "/workspace/mmaction2/configs/skeleton/stgcnpp/stgcnpp_enhanced_fight_detection_stable.py"
    checkpoint_path: "/workspace/mmaction2/work_dirs/stgcnpp-bone-ntu60_rtmo-m_RWF2000plus_stable/best_acc_top1_epoch_14.pth"
    device: "cuda:0"
    window_size: 100
    class_names: ["NonFight", "Fight"]
    confidence_threshold: 0.4
    num_classes: 2
    input_format: "stgcn"
    expected_keypoint_count: 17
    coordinate_dimensions: 2
    max_persons: 4

# 공통 성능 설정
performance:
  # 기본 디바이스
  device: "cuda:0"
  
  # 윈도우 설정
  window_size: 100
  window_stride: 50
  inference_stride: 25
  batch_size: 8
  
  # 멀티GPU 설정
  multi_gpu:
    enable: false
    gpus: [0, 1]
    strategy: "data_parallel"
    batch_per_gpu: 8
  
  # 멀티프로세스 설정
  multiprocess:
    enable: false
    workers: 4
    strategy: "pipeline"
    shared_memory: true
    queue_size: 100
    timeout: 600.0
  
  # 최적화 옵션
  mixed_precision: false
  enable_tensorrt: false
  enable_torch_compile: false

# 로깅 설정
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  save_to_file: true
  
# 출력 설정
output:
  # 디렉토리 구조
  create_subdirs: true
  subdir_names:
    stage1: "stage1_poses"
    stage2: "stage2_tracking"
    stage3: "stage3_results"
    evaluation: "evaluation"
    visualizations: "visualizations"
    logs: "logs"
  
  # 파일 명명 규칙
  naming:
    include_timestamp: true
    include_mode: true

# 메모리 관리
memory_management:
  enable_garbage_collection: true
  gc_interval: 100
  max_cache_size: 1000

# 오류 처리
error_handling:
  continue_on_error: true
  max_consecutive_errors: 10
  error_recovery_strategy: "skip"