mode: inference.realtime


annotation:
  input: /workspace/recognizer/test_data
  output_dir: output
  pipeline_mode: true

  stage1:
    enabled: true
  stage2:
    enabled: true
  stage3:
    enabled: true
    split_ratios:
      train: 0.7
      val: 0.2
      test: 0.1

  visualize:
    stage: stage2
    video_dir: /workspace/recognizer/test_data
    results_dir: output/test_data/stage2_tracking/bytetrack_h0.3_l0.1_t0.2
    save_mode: true

inference:
  analysis:
    input: /aivanas/raw/surveillance/action/violence/action_recognition/data/UBI_FIGHTS/videos/normal/N_9_0_0_1_0.mp4
    output_dir: output

  realtime:
    input: /aivanas/raw/surveillance/action/violence/action_recognition/data/UBI_FIGHTS/videos/fight/F_77_1_0_0_0.mp4
    output_path: output
    save_output: true
    display_width: 640
    display_height: 480
    # 오버레이 표시 모드 설정
    overlay_mode: full  # full, skeleton_only, raw

  visualize:
    input: /aivanas/raw/surveillance/action/violence/action_recognition/data/UBI_FIGHTS/videos/normal/N_9_0_0_1_0.mp4
    results_dir: /workspace/recognizer/output/N_9_0_0_1_0
    save_dir: /workspace/recognizer/output/N_9_0_0_1_0
    save_mode: true


models:
  action_classification:
    checkpoint_path: /workspace/mmaction2/work_dirs/stgcnpp-bone-ntu60_rtmo-m_RWF2000plus_stable/best_acc_top1_epoch_14.pth
    class_names:
    - NonFight
    - Fight
    confidence_threshold: 0.4
    config_file: /workspace/mmaction2/configs/skeleton/stgcnpp/stgcnpp_enhanced_fight_detection_stable.py
    coordinate_dimensions: 2
    device: cuda:0
    expected_keypoint_count: 17
    input_format: stgcn
    max_persons: 4
    model_name: stgcn
    num_classes: 2
    window_size: 100

  pose_estimation:
    inference_mode: onnx 
    onnx:
      arena_extend_strategy: kNextPowerOfTwo
      backend: onnxruntime
      benchmark_info:
        benchmark_date: '2025-08-20 00:26:52'
        gpu_name: NVIDIA RTX A5000
        onnxruntime_version: 1.18.0
        optimized_fps: 0
      cudnn_conv_algo_search: HEURISTIC
      cudnn_conv_use_max_workspace: true
      device: cuda:0
      do_copy_in_default_stream: false
      enable_cpu_mem_arena: true
      enable_mem_pattern: true
      execution_mode: ORT_SEQUENTIAL
      gpu_mem_limit_gb: 8
      graph_optimization_level: ORT_ENABLE_ALL
      keypoint_threshold: 0.3
      max_detections: 100
      mean: null
      model_input_size:
      - 640
      - 640
      model_name: rtmo_onnx
      model_path: /workspace/mmpose/checkpoints/end2end.onnx
      nms_threshold: 0.45
      score_threshold: 0.3
      std: null
      to_openpose: false
      tunable_op_enable: true
      tunable_op_tuning_enable: true

    pth:
      checkpoint_path: /workspace/mmpose/checkpoints/rtmo-m_16xb16-600e_body7-640x640-39e78cc4_20231211.pth
      config_file: /workspace/mmpose/configs/body_2d_keypoint/rtmo/body7/rtmo-m_16xb16-600e_body7-640x640.py
      device: cuda:0
      input_size:
      - 640
      - 640
      model_name: rtmo
      score_threshold: 0.2
      nms_threshold: 0.65
      keypoint_threshold: 0.3

    tensorrt:
      device: cuda:0
      fp16_mode: false
      keypoint_threshold: 0.3
      max_detections: 100
      mean: null
      model_input_size:
      - 640
      - 640
      model_name: rtmo_tensorrt
      model_path: /workspace/mmpose/checkpoints/rtmo.trt
      nms_threshold: 0.45
      score_threshold: 0.3
      std: null
      to_openpose: false

  scoring:
    min_track_length: 10
    quality_threshold: 0.3
    scorer_name: region_based
    weights:
      appearance: 0.05
      interaction: 0.4
      movement: 0.3
      position: 0.05
      posture: 0.1
      temporal: 0.1

  tracking:
    frame_rate: 30
    iou_weight: 0.7
    keypoint_weight: 0.3
    match_thresh: 0.5
    match_thresh_second: 0.4
    min_box_area: 100
    mot20: false
    new_track_thresh: 0.5
    track_buffer: 120
    track_high_thresh: 0.3
    track_low_thresh: 0.1
    track_thresh: 0.2
    tracker_name: bytetrack
    use_hybrid_matching: true


performance:
  batch_size: 8
  device: cuda:0
  enable_garbage_collection: true
  gc_interval: 100
  max_cache_size: 1000
  window_size: 100
  window_stride: 50


events:
  # 이벤트 발생 조건
  alert_threshold: 0.7                    # 폭력 탐지 신뢰도 임계값
  min_consecutive_detections: 3           # 연속 탐지 최소 횟수
  
  # 이벤트 해제 조건  
  normal_threshold: 0.5                   # 정상 상태 신뢰도 임계값
  min_consecutive_normal: 5               # 연속 정상 최소 횟수
  
  # 시간 기반 조건
  min_event_duration: 2.0                 # 최소 이벤트 지속 시간 (초)
  max_event_duration: 300.0               # 최대 이벤트 지속 시간 (초) 
  cooldown_duration: 10.0                 # 이벤트 쿨다운 시간 (초)
  
  # 알림 설정
  enable_ongoing_alerts: true             # 진행 중 알림 활성화
  ongoing_alert_interval: 30.0            # 진행 중 알림 간격 (초)
  
  # 로그 설정
  save_event_log: true                    # 이벤트 로그 저장 여부
  event_log_format: json                  # 로그 형식 (json/csv)
  event_log_path: output/event_logs       # 이벤트 로그 저장 경로


files:
  naming:
    include_timestamp: false
    poses_suffix: _frame_poses
    results_suffix: _results
    rtmo_suffix: _rtmo_poses
  output_structure:
    json_dir: json
    overlay_dir: overlay
    pkl_dir: pkl
  video_extensions:
  - .mp4
  - .avi
  - .mov
  - .mkv
  - .flv
  - .wmv


logging:
  format: '%(asctime)s - %(levelname)s - %(message)s'
  level: WARNING


error_handling:
  continue_on_error: true
  error_recovery_strategy: skip
  max_consecutive_errors: 10