# mode: inference.analysis
# mode: inference.visualize
# mode: inference.realtime
mode: annotation.stage3
# mode: annotation.visualize

# 듀얼 서비스 설정
dual_service:
  # enabled: true                            # 듀얼 서비스 활성화
  enabled: false                         # 단일 서비스 모드
  services:
    # - fight                              # Fight 탐지 서비스
    - falldown                           # Falldown 탐지 서비스

annotation:
  input: /aivanas/raw/surveillance/action/violence/action_recognition/data/falldown_aihub_backup
  output_dir: output
  pipeline_mode: true

  stage1:
    enabled: true
    # Stage1 전용 멀티 프로세스 설정
    multi_process:
      enabled: true                     # Stage1 멀티프로세스 활성화
      num_processes: 16                  # 프로세스 수
      gpus: [0, 1]                      # 사용할 GPU 목록 (라운드 로빈 할당)
      chunk_strategy: video_split       # 비디오 단위로 분할
  stage2:
    enabled: true
  stage3:
    enabled: true
    split_ratios:
      train: 0.7
      val: 0.2
      test: 0.1

  visualize:
    stage: stage2
    video_dir: /aivanas/raw/surveillance/action/violence/action_recognition/data/falldown_aihub
    results_dir: /workspace/recognizer/output/falldown_aihub/stage2_tracking/bytetrack_h0.4_l0.1_t0.2
    save_mode: false

inference:
  analysis:
    input: /aivanas/raw/surveillance/action/violence/action_recognition/data/UBI_demo
    output_dir: output

    # 성능평가 설정
    enable_evaluation: true          # 성능평가 기능 활성화

    # Inference Analysis 전용 멀티 프로세스 설정
    multi_process:
      enabled: true                  # Inference Analysis 멀티프로세스 활성화
      num_processes: 4               # 프로세스 수
      gpus: [0, 1]                   # 사용할 GPU 목록 (라운드 로빈 할당)
      chunk_strategy: video_split    # 비디오 단위로 분할

  realtime:
    input: /aivanas/raw/surveillance/action/violence/action_recognition/data/UBI_demo
    # input: /aivanas/raw/surveillance/action/violence/action_recognition/data/falldown_aihub
    output_path: /workspace/recognizer/output 
    save_output: true
    display_width: 640
    display_height: 480
    # 오버레이 표시 모드 설정
    overlay_mode: skeleton_only  # full, skeleton_only, raw

  visualize:
    input: /aivanas/raw/surveillance/action/violence/action_recognition/data/UBI_demo
    results_dir: /workspace/recognizer/output/UBI_demo
    save_dir: /workspace/recognizer/output/UBI_demo
    save_mode: true


# 듀얼 서비스 모델 설정
models:
  # Fight 탐지 모델
  fight_classification:
    checkpoint_path: /workspace/mmaction2/work_dirs/stgcnpp-bone-ntu60_rtmo-l_RWF2000plus_stable/best_acc_top1_epoch_30.pth
    class_names:
    - NonFight
    - Fight
    confidence_threshold: 0.4
    config_file: /workspace/mmaction2/configs/skeleton/stgcnpp/stgcnpp_enhanced_fight_detection_stable.py
    coordinate_dimensions: 2
    device: cuda:0
    expected_keypoint_count: 17
    input_format: stgcn
    max_persons: 4
    model_name: stgcn
    num_classes: 2
    window_size: 100

  # Falldown 탐지 모델
  falldown_classification:
    checkpoint_path: /workspace/mmaction2/work_dirs/stgcnpp-bone-ntu60_rtmo-l_falldown_aihub_stable/best_acc_top1_epoch_2.pth
    class_names:
    - Normal
    - Falldown
    confidence_threshold: 0.4
    config_file: /workspace/mmaction2/configs/skeleton/stgcnpp/stgcnpp_enhanced_falldown_detection_stable.py
    coordinate_dimensions: 2
    device: cuda:0
    expected_keypoint_count: 17
    input_format: stgcn
    max_persons: 4
    model_name: stgcn
    num_classes: 2
    window_size: 100

# 포즈 추정 탐지 모델
  pose_estimation:
    inference_mode: onnx 
    onnx:
      arena_extend_strategy: kNextPowerOfTwo
      backend: onnxruntime
      benchmark_info:
        benchmark_date: '2025-08-20 00:26:52'
        gpu_name: NVIDIA RTX A5000
        onnxruntime_version: 1.18.0
        optimized_fps: 0
      cudnn_conv_algo_search: HEURISTIC
      cudnn_conv_use_max_workspace: true
      device: cuda:0
      do_copy_in_default_stream: false
      enable_cpu_mem_arena: true
      enable_mem_pattern: true
      execution_mode: ORT_SEQUENTIAL
      gpu_mem_limit_gb: 8
      graph_optimization_level: ORT_ENABLE_ALL
      keypoint_threshold: 0.3
      max_detections: 100
      mean: null
      model_input_size:
      - 640
      - 640
      model_name: rtmo_onnx
      model_path: /workspace/mmpose/checkpoints/end2end_l.onnx
      # model_path: /workspace/mmpose/checkpoints/end2end_m.onnx
      nms_threshold: 0.45
      score_threshold: 0.3
      std: null
      to_openpose: false
      tunable_op_enable: true
      tunable_op_tuning_enable: true

    pth:
      # checkpoint_path: /workspace/mmpose/checkpoints/rtmo-m_16xb16-600e_body7-640x640-39e78cc4_20231211.pth
      # config_file: /workspace/mmpose/configs/body_2d_keypoint/rtmo/body7/rtmo-m_16xb16-600e_body7-640x640.py
      checkpoint_path: /workspace/mmpose/checkpoints/rtmo-l_16xb16-600e_body7-640x640-b37118ce_20231211.pth
      config_file: /workspace/mmpose/configs/body_2d_keypoint/rtmo/body7/rtmo-l_16xb16-600e_body7-640x640.py
      device: cuda:0
      input_size:
      - 640
      - 640
      model_name: rtmo
      score_threshold: 0.2
      nms_threshold: 0.65
      keypoint_threshold: 0.3

    tensorrt:
      device: cuda:0
      fp16_mode: false
      keypoint_threshold: 0.3
      max_detections: 100
      mean: null
      model_input_size:
      - 640
      - 640
      model_name: rtmo_tensorrt
      model_path: /workspace/mmpose/checkpoints/rtmo.trt
      nms_threshold: 0.45
      score_threshold: 0.3
      std: null
      to_openpose: false

# 트래킹 설정
  tracking:
    frame_rate: 30
    iou_weight: 0.7
    keypoint_weight: 0.정정
    match_thresh: 0.5
    match_thresh_second: 0.4
    min_box_area: 100
    mot20: false
    new_track_thresh: 0.5
    track_buffer: 120
    track_high_thresh: 0.4
    track_low_thresh: 0.1
    track_thresh: 0.2
    tracker_name: bytetrack
    use_hybrid_matching: true

# 듀얼 서비스 스코어링 설정
  scoring:
    # Fight 스코어링
    fight:
      min_track_length: 10
      quality_threshold: 0.3
      scorer_name: region_based
      weights:
        movement: 0.4
        interaction: 0.4
        position: 0.1
        temporal: 0.1
    
    # Falldown 스코어링
    falldown:
      min_track_length: 10
      quality_threshold: 0.3
      scorer_name: falldown_scorer
      weights:
        height_change: 0.35
        posture_angle: 0.25
        movement_intensity: 0.20
        persistence: 0.15
        position: 0.05
    
    # 기존 호환성 (fight와 동일)
    min_track_length: 10
    quality_threshold: 0.3
    scorer_name: region_based
    weights:
      movement: 0.4
      interaction: 0.4
      position: 0.1
      temporal: 0.1



performance:
  batch_size: 8
  device: cuda:0
  enable_garbage_collection: true
  gc_interval: 100
  max_cache_size: 1000
  window_size: 100
  window_stride: 50


# 듀얼 서비스 이벤트 설정
events:
  # Fight 이벤트 설정
  fight:
    alert_threshold: 0.8                    # Fight 탐지 신뢰도 임계값
    min_consecutive_detections: 3           # 연속 탐지 최소 횟수
    normal_threshold: 0.5                   # 정상 상태 신뢰도 임계값
    min_consecutive_normal: 2               # 연속 정상 최소 횟수
    min_event_duration: 2.0                 # 최소 이벤트 지속 시간 (초)
    max_event_duration: 10.0               # 최대 이벤트 지속 시간 (초) 
    cooldown_duration: 5.0                 # 이벤트 쿨다운 시간 (초)
  
  # Falldown 이벤트 설정
  falldown:
    alert_threshold: 0.6                    # Falldown 탐지 신뢰도 임계값 (낮게 설정)
    min_consecutive_detections: 2           # 연속 탐지 최소 횟수 (빠른 반응)
    normal_threshold: 0.4                   # 정상 상태 신뢰도 임계값
    min_consecutive_normal: 3               # 연속 정상 최소 횟수 (확실한 해제)
    min_event_duration: 1.0                 # 최소 이벤트 지속 시간 (초, 빠른 탐지)
    max_event_duration: 15.0               # 최대 이벤트 지속 시간 (초, 길게 설정)
    cooldown_duration: 3.0                 # 이벤트 쿨다운 시간 (초, 짧게 설정)
  
  # 공통 설정 (기존 호환성)
  alert_threshold: 0.8                    # 기본 탐지 신뢰도 임계값
  min_consecutive_detections: 3           # 연속 탐지 최소 횟수
  normal_threshold: 0.5                   # 정상 상태 신뢰도 임계값
  min_consecutive_normal: 2               # 연속 정상 최소 횟수
  min_event_duration: 2.0                 # 최소 이벤트 지속 시간 (초)
  max_event_duration: 10.0               # 최대 이벤트 지속 시간 (초) 
  cooldown_duration: 5.0                 # 이벤트 쿨다운 시간 (초)
  
  # 알림 설정
  enable_ongoing_alerts: true             # 진행 중 알림 활성화
  ongoing_alert_interval: 30.0            # 진행 중 알림 간격 (초)
  
  # 로그 설정
  save_event_log: true                    # 이벤트 로그 저장 여부
  event_log_format: json                  # 로그 형식 (json/csv)
  event_log_path: output/event_logs       # 이벤트 로그 저장 경로


files:
  naming:
    include_timestamp: false
    poses_suffix: _frame_poses
    results_suffix: _results
    rtmo_suffix: _rtmo_poses
  output_structure:
    json_dir: json
    overlay_dir: overlay
    pkl_dir: pkl
  video_extensions:
  - .mp4
  - .avi
  - .mov
  - .mkv
  - .flv
  - .wmv


logging:
  format: '%(asctime)s - %(levelname)s - %(message)s'
  level: WARNING


error_handling:
  continue_on_error: true
  error_recovery_strategy: skip
  max_consecutive_errors: 10