# 실시간 추론 파이프라인 설정 파일
# base_config.yaml을 상속하여 실시간 추론 특화 설정

# 베이스 설정 상속
base_config: "configs/base_config.yaml"

# 실시간 추론 특화 설정
realtime_inference:
  # 큐 설정
  max_queue_size: 200
  result_queue_size: 100
  
  # 프레임 처리 설정
  target_fps: 30
  skip_frames: 1
  resize_input: null  # [width, height] 또는 null
  
  # 알림 설정
  alert_threshold: 0.5
  min_confidence: 0.5
  
  # 콜백 설정
  enable_alert_callback: true
  enable_frame_callback: true

# 성능 설정 오버라이드
performance:
  # 실시간 처리를 위한 최적화
  batch_size: 1
  inference_stride: 10  # 더 빠른 추론
  
  # 메모리 관리 (실시간 처리용)
  memory_management:
    enable_garbage_collection: true
    gc_interval: 30
    max_cache_size: 500

# 출력 설정 오버라이드
output:
  base_dir: "output/inference"
  log_file: "logs/inference.log"
  
  # 실시간 로깅 설정
  realtime_logging:
    log_alerts: true
    log_performance: true
    log_interval: 10  # seconds