# Recognizer 메인 설정 파일
# base_config.yaml을 상속하여 특정 설정만 오버라이드

# 베이스 설정 상속
base_config: "configs/base_config.yaml"

# 실행 모드 설정
execution:
  mode: "inference"
  input: "data/test_video.mp4"
  output_dir: "output/main_results"

# 기능 활성화 설정
features:
  enable_evaluation: true
  enable_visualization: true
  enable_gpu_acceleration: true

# 모드별 설정
modes:
  # 추론 모드 설정
  inference:
    source_type: "file"
    target_fps: 30.0
    realtime:
      max_queue_size: 200
      skip_frames: 1
      alert_threshold: 0.5
      min_confidence: 0.5
  
  # 분리 파이프라인 모드 설정
  separated:
    enable_resume: true
    stages:
      stage1_pose: true
      stage2_tracking: true
      stage3_classification: true
  
  # 통합 파이프라인 모드 설정
  unified:
    save_intermediate_results: false
    enable_progress_callback: true

# 평가 설정
evaluation:
  class_names: ["NonFight", "Fight"]
  save_options:
    detailed_results: true
    performance_metrics: true
  metrics:
    calculate_confusion_matrix: true
    calculate_per_class_metrics: true

# 시각화 설정
visualization:
  types:
    performance_charts: true
    timeline_visualization: true
    confusion_matrix: true
  quality:
    video_fps: 30.0
    video_quality: "high"