# 분리형 파이프라인 설정 파일
# base_config.yaml을 상속하여 분리형 파이프라인 특화 설정

# 베이스 설정 상속
base_config: "configs/base_config.yaml"

# 분리형 파이프라인 특화 설정
separated_pipeline:
  # 스테이지별 출력 디렉토리
  stage1_output_dir: "output/separated/stage1_poses"
  stage2_output_dir: "output/separated/stage2_tracking"
  stage3_output_dir: "output/separated/stage3_results"
  stage4_output_dir: "output/separated/stage4_unified"
  
  # Resume 기능
  enable_resume: true
  
  # 처리 옵션
  validate_inputs: true
  save_intermediate: true
  profile_performance: true

# 멀티프로세스 설정 오버라이드
performance:
  multiprocess:
    enable: true
    workers: 8
    batch_size: 4
    timeout: 600.0

# 출력 설정 오버라이드
output:
  base_dir: "output/separated"
  log_file: "logs/separated_pipeline.log"

# 성능 모니터링
performance_monitoring:
  enable_monitoring: true
  monitoring_interval: 30
  metrics_to_track:
    - "processing_time"
    - "memory_usage"
    - "stage_success_rate"
    - "error_rate"