# 통합 파이프라인 설정 파일
# base_config.yaml을 상속하여 통합 파이프라인 특화 설정

# 베이스 설정 상속
base_config: "configs/base_config.yaml"

# 통합 파이프라인 특화 설정
unified_pipeline:
  # 중간 결과 저장 여부
  save_intermediate_results: false
  
  # 진행률 콜백 활성화
  enable_progress_callback: true
  enable_result_callback: true
  
  # 배치 처리 설정
  max_batch_size: 16
  
# 출력 설정 오버라이드
output:
  base_dir: "output/unified"
  log_file: "logs/unified_pipeline.log"
  
  # 결과 저장 형식
  save_formats:
    - "pkl"     # 기본 pickle 형식
    - "json"    # JSON 형식 (메타데이터)
    
# 성능 최적화
performance:
  # 배치 크기 최적화
  batch_size: 16
  
  # 메모리 관리
  memory_management:
    enable_garbage_collection: true
    gc_interval: 50
    max_cache_size: 2000