# 시각화 모드 예시 설정
execution:
  mode: "visualize"

visualization:
  results_dir: "analysis_results"        # 분석 결과가 있는 디렉토리
  video_file: "/path/to/video.mp4"      # 원본 비디오 파일
  # video_dir: "/path/to/video_folder"  # 원본 비디오 폴더 (video_file과 둘 중 하나만)
  save_mode: true                       # true: 저장, false: 실시간 표시
  save_dir: "overlay_videos"