# ONNX Conversion Configuration
# PyTorch to ONNX 변환을 위한 설정 파일

# 모델 경로 설정
model:
  config_path: "/home/gaonpf/hsnam/mmlabs/mmaction2/configs/skeleton/stgcnpp/stgcnpp_enhanced_fight_detection_stable.py"
  checkpoint_path: "/home/gaonpf/hsnam/mmlabs/mmaction2/work_dirs/stgcnpp-bone-ntu60_rtmo-m_RWF2000plus_stable/best_acc_top1_epoch_14.pth"
  output_path: "/home/gaonpf/hsnam/mmlabs/checkpoints/stgcn_fight_detection.onnx"

# 입력 데이터 형태 설정
input_shape:
  batch_size: 1
  num_frames: 100      # 시간축 (T)
  num_persons: 4       # 최대 인원 수 (M)  
  num_keypoints: 17    # COCO 키포인트 수 (V)
  keypoint_dim: 2      # 2D 좌표 (C)

# 동적 축 설정 (Dynamic Shape)
dynamic_axes:
  enable: true
  batch_size: true     # 배치 크기 동적
  num_frames: true     # 프레임 수 동적 (윈도우 크기 가변)
  num_persons: false   # 인원 수 고정 (성능 최적화)

# ONNX 변환 설정
conversion:
  opset_version: 11    # ONNX opset 버전
  optimize: true       # 상수 폴딩 최적화
  verbose: false       # 상세 로깅

# 검증 및 성능 측정
validation:
  verify_output: true  # 출력 결과 검증
  tolerance: 1e-3      # 허용 오차
  benchmark: true      # 성능 벤치마크
  benchmark_runs: 100  # 벤치마크 실행 횟수
  warmup_runs: 10      # 워밍업 실행 횟수

# 디바이스 설정
device: "cuda:0"       # 또는 "cpu"

# 사전 정의된 프리셋
presets:
  # 실시간 추론용 (동적 크기, 최적화)
  realtime:
    input_shape:
      batch_size: 1
      num_frames: 100
    dynamic_axes:
      enable: true
      batch_size: false
      num_frames: true
    conversion:
      opset_version: 11
      optimize: true
  
  # 배치 처리용 (정적 크기, 고성능)  
  batch_processing:
    input_shape:
      batch_size: 8
      num_frames: 100
    dynamic_axes:
      enable: false
    conversion:
      opset_version: 11
      optimize: true
  
  # 개발/디버깅용 (정적 크기, 검증 강화)
  development:
    input_shape:
      batch_size: 1
      num_frames: 100
    dynamic_axes:
      enable: false
    conversion:
      opset_version: 11
      optimize: false
    validation:
      verify_output: true
      tolerance: 1e-5
      benchmark: true